language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
    - master
install:
  - npm install yarn
before_script:
  # 把项目下的deploy_rsa.enc加密文件，解密输出到/tmp/deploy_rsa中
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 /tmp/deploy_rsa
  # 将私钥添加到 ssh
  - ssh-add /tmp/deploy_rsa
script:
  - yarn build
after_success:
  - echo "success!"
services:
  - docker
addons:
  ssh_known_hosts:
    - 49.235.118.244
after_success:
  - ssh mrli@49.235.118.244 -o stricthostkeychecking=no "mkdir travis_deploy_success"