language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
    - master

install:
  - npm install yarn

addons:
  ssh_known_hosts:
    - 49.235.118.244

env:
  global:
    - IMAGE_NAME=nymrli/sucsoft-inititializer-front
    - IMAGE_TAG=latest

before_script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  # 把项目下的deploy_rsa.enc加密文件，解密输出到/tmp/deploy_rsa中
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 /tmp/deploy_rsa
  # 将私钥添加到 ssh
  - ssh-add /tmp/deploy_rsa

script:
  - yarn build

after_success:
  - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
  - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  # 删除已有镜像并删除
  - ssh mrli@49.235.118.244 -o stricthostkeychecking=no "echo ${IMAGE_TAG};docker rmi $(docker images | grep "nymrli/sucsoft-inititializer-front" | awk '{if($2~/^$${IMAGE_TAG}$/)print $3}')
;docker run -d --name cgf -p 3000:80 ${IMAGE_NAME}"
  - echo "success!"
  
services:
  - docker